server:
  port: 8104

spring:
  application:
    name: search-service
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: ${JWT_SECRET:change-me-very-long-secret-32bytes+}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    consumer:
      group-id: search-indexer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

search:
  index: catalog

opensearch:
  url: ${OPENSEARCH_URL:http://localhost:9200}
