server:
  port: 8105

spring:
  application:
    name: auth-service

jwt:
  expires-min: 60
  refresh-expires-min: 1440

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
