server:
  port: 8102

spring:
  application:
    name: rank-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    streams:
      application-id: rank-service
      state-dir: ${TMPDIR:/tmp}/kstreams
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      properties:
        spring.json.trusted.packages: "*"
    properties:
      spring.json.trusted.packages: "*"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8105/.well-known/jwks.json}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

springdoc:
  swagger-ui:
    enabled: true

rank:
  windows: "10s,60s,300s"
  ttlFactor: 3  # Each ZSET expires after (windowSec * ttlFactor) seconds
  aggregateMax: 5
  aggregateReadFactor: 3  # Each window reads top (n * factor) entries when aggregating
