# Production environment values for auth-service

replicaCount: 3

image:
  repository: msa-webtoon/auth-service
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets:
  - name: registry-credentials

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

env:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8105"
  MANAGEMENT_SERVER_PORT: "8105"
  # JWT Configuration - standard expiration
  JWT_ACCESS_TOKEN_EXPIRATION_MINUTES: "60"  # 1 hour
  JWT_REFRESH_TOKEN_EXPIRATION_DAYS: "30"  # 30 days
  # Logging
  LOGGING_LEVEL_ROOT: "WARN"
  LOGGING_LEVEL_COM_YOORDI: "INFO"

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - auth-service
        topologyKey: kubernetes.io/hostname
