apiVersion: v2
name: api-gateway
description: API Gateway service for MSA-Webtoon platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: "0.1.0"
    repository: "file://../common"
