# Development environment values for api-gateway
# Override base values.yaml settings

replicaCount: 1  # Single replica for dev

image:
  repository: msa-webtoon/api-gateway
  pullPolicy: Always  # Always pull latest for dev
  tag: "dev-latest"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false  # Disable HPA in dev

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  MANAGEMENT_SERVER_PORT: "8080"
  # Redis configuration
  SPRING_DATA_REDIS_HOST: "localhost"
  SPRING_DATA_REDIS_PORT: "6379"
  # Logging - verbose for dev
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_YOORDI: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "DEBUG"
  # CORS - permissive for dev
  CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:8080,http://127.0.0.1:3000"
  # Circuit Breaker - more lenient
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_FAILURERATE_THRESHOLD: "70"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_DEFAULT_WAIT_DURATION_IN_OPEN_STATE: "5s"

livenessProbe:
  initialDelaySeconds: 30  # Faster startup
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5

ingress:
  enabled: false  # No ingress in dev (use port-forward)
