server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - AddResponseHeader=X-Gateway,msa-webtoon
      routes:
        - id: ingest
          uri: ${SERVICE_EVENT_INGEST_URL:http://localhost:8101}
          predicates:
            - Path=/ingest/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 200   # 초당 200
                redis-rate-limiter.burstCapacity: 400
        - id: rank
          uri: ${SERVICE_RANK_URL:http://localhost:8102}
          predicates:
            - Path=/rank/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 300
                redis-rate-limiter.burstCapacity: 600
        - id: catalog
          uri: ${SERVICE_CATALOG_URL:http://localhost:8103}
          predicates:
            - Path=/catalog/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
        - id: search
          uri: ${SERVICE_SEARCH_URL:http://localhost:8104}
          predicates:
            - Path=/search/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 200
                redis-rate-limiter.burstCapacity: 400
        - id: generator
          uri: ${SERVICE_GENERATOR_URL:http://localhost:8083}
          predicates:
            - Path=/generator/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
      httpclient:
        connect-timeout: 3000
        response-timeout: 5s

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  webflux:
    base-path: /
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: "*"
          allowed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  swagger-ui:
    enabled: true

jwt:
  secret: ${JWT_SECRET:change-me-very-long-secret-32bytes+}

