# Development environment values for event-generator
# Override base values.yaml settings

replicaCount: 1

image:
  repository: msa-webtoon/event-generator
  pullPolicy: Always  # Always pull latest for dev
  tag: "dev-latest"

resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  MANAGEMENT_SERVER_PORT: "8080"
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
  # Event generation settings - lower rate for dev
  GENERATOR_AUTO_START: "false"
  GENERATOR_DEFAULT_EPS: "10"
  # Logging - verbose for dev
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_COM_YOORDI: "DEBUG"

livenessProbe:
  initialDelaySeconds: 30  # Faster startup
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 15
  periodSeconds: 5
