# Production environment values for catalog-service

replicaCount: 3

image:
  repository: msa-webtoon/catalog-service
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

imagePullSecrets:
  - name: registry-credentials

resources:
  limits:
    cpu: 1500m
    memory: 1.5Gi
  requests:
    cpu: 750m
    memory: 768Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 12
  targetCPUUtilizationPercentage: 65
  targetMemoryUtilizationPercentage: 75

env:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8083"
  MANAGEMENT_SERVER_PORT: "8083"
  # Kafka configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  # PostgreSQL configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/catalog"
  SPRING_DATASOURCE_USERNAME: "catalog_user"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "none"
  SPRING_JPA_SHOW_SQL: "false"
  SPRING_FLYWAY_ENABLED: "true"
  # Connection pool
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "20"
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: "5"
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "30000"
  # Logging
  LOGGING_LEVEL_ROOT: "WARN"
  LOGGING_LEVEL_COM_YOORDI: "INFO"

envSecrets:
  SPRING_DATASOURCE_PASSWORD:
    name: catalog-service-secrets
    key: postgres-password
  AUTH_JWKS_URI:
    name: catalog-service-secrets
    key: auth-jwks-uri

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - catalog-service
        topologyKey: kubernetes.io/hostname
