pipeline {
  agent any
  stages {
    stage('Build') { steps { sh './gradlew clean build -x test' } }
    stage('Test')  { steps { sh './gradlew test' } }
    stage('Images'){ steps { sh './gradlew :services:rank-service:jib -x test' } }
    stage('Helm')  { steps { sh 'helm upgrade --install rank-service platform/helm/charts/rank-service -n apps' } }
  }
}